apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-example
  namespace: argo-workflows
spec:
  serviceAccountName: argo-workflows-server
  entrypoint: hello-argo
  templates:
  - name: hello-argo
    container:
      image: ubuntu:latest
      command: ["echo"]
      args: ["Hello, Argo!"]
