apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-workspace
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  source:
    path: "icdev-01/crossplane-workspace/resources"
    repoURL: "git@github.com:ValeriiVasianovych/GitOps-ArgoCD-Infrastructure.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
