---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: sealed-secret
spec:
  encryptedData:
    creds: AgAILzxPZqRTb6fRwCL8xxwXAaEuqx9TTYw/Yjchyzit58+N/xAWJ8lCvZCbv7dZS8x2ORJ8DBo4qm+yg4KcS7ZIt5ZhjIIHxdrxr359lCOT+18FslkfO4QjeGQy3eWrUXXjPbTrUVFn4sxxdiJjaBhUVjUZ14315eWFR2ugtb+hIa8PmkDkn1efjcW+hjTxEkMT2MFeucBSwA09dSkVHCKKqOLc730nZquerNONQUX57LDB7CBwqXuujCXivnXNoH/vfZ7nm+ItdGqg2uR9QYRCjMP2V6XDIQTt01AHTa/6KdBN77ONOfBU0qpqRrfSplqu0bEPJWq24lfWscx4FhISehxTJVWBK8cRUP4N4magAu2qO1qr5kzZHMpO2bdr7mIf+YAbol7OX6E1UP16Y6dGNCGzpJS/qhfdkbRDzzIqeB94vsBOYBM/FA4QLPEN74BB6HxAh39S7+Q0zUYWBBQMRWZa+xq9YcuQhbTODjTUz0ZY3WYA9TjpNBkdK0l4/eRWpRY+BSIvnVL+wl3OoDye/9lJKnNwAdqDWyQ7h1SN4FrN61KD1hBiIC3cxwJSBuqbW2T0jkBKG9d89esfRPwi+Ax9g/6i6GQXRzypA8jgmXRtHY/YOHPqV5ZRIR8s7tJ2kfOUft+vcSguXYApc6BZ56HnvRKw/4psZ7rn/7apeN1L5LIWww2sgxaTcuHxGGbn2gntG2k0QKdcPIvMtuiPhCG5sjLw82gZIVRNtKLSK9/yXLpDUAJkq0jyxAeKyUjFUB4SZzq8ecM9xnlEmdk/N2fgXmlovFwqVpbbqRPljKcAO9/o/9uT6bTGE1eQ6h+MNi6+7Zsc/sbLiLYJztMvFJM2tQ==
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: sealed-secret
