apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: crossplane-system
spec:
  encryptedData:
    aws_access_key_id: AgCSSmO0eiD0OZVnJZryJdhEonZY3D/1lFaE4l6l65iU2XYF1nQ2VpHsSPJRgGetd877xEOLFnN8lIzXgwRCxsF3poUKR9aaSPY2aabN/4sAfIwUc7HrLDFjMd6VWnutcdyS+FNJa99JkdHzo0rEf/0a7ti5cPp5XLqAz2vkrbsXz6Rrh66f2s+CZ1A2uKEzOBetUz8ZEi+OKOFYdzo1+9Umhbemf3gcAA0gqmS16KojXZplmMVBFtlxDFoE13l9kgBMaRgVVC8MQsJ+iA2EcVCvdRz4nNqOSOpUVPerRSyTCFWcMvUjzRD2mr73UH/7QZUKKomvl2b7I8P54OYPyfaatCx5J7r0OoITjanUYJXeh8uOfHNwgmeGQa0s5wBBgQdGVnsehISRqdrGLxFplkyVtrPCw40RET0sLPw1AE84WHv/t4ouDqCL0YrPiAIzXP+aQ/bm9UyMRxJhcLY0w3liRi84NRzDiQkxngNkAKWKvPKjjx2huz8o+Naz5hjVOwGSo2r0K+9X3xEzLXnW8g0CYqCvPj1+L2RVuC8+HH4pWEDEGY5tgV8RX9uJaiIVrIuN7kVoYTEzXo3bLqWniFUw0Ba3asAacqY/f8w2z/JtB1kyi+MFnqQf2GjcOVaCHNiCLL1CEHzr0nEX6ecYb9R3qqeRb59MZSjnLnpDNkhFr9+RZ5qeRvO4rhMhVZ2OvnzecBctVenw+Y58f5qZ+yvvuxIDOLs=
    aws_secret_access_key: AgAiMeefrvTl1s1DaJTbA1Tu48c7FsFEc6r87cwr9BBDhIocTXN2GOLsSYJbmKmlOlCsUMPE9sqXhsOFQpaCxR4baDoz6zn3y+7Uti3zTpqEFwgP7XqHe5jFYzYRw0I2ZLtzWHzUBGg3ymCcBgQgszRlNMQIYlMzlD7+7KiU5wEI5zHEIahyZ4964fHM9ps4QTmcpTlsyuAkiOLBqfGhBih9tn82G0Uocd9Uipd+rPM7LL7QUqBxcyAIaJTjEJepBAqWW/xFjOvuKn9rxOxdiWySKgx7AjuRFVOzydGtix7RYNMrAwwxURzA2es3nJtcBYljaNc0BX0Z24ltnrNAK+QcNA9RCWNv6jjHrCTGdqTVITpn/RPBYXlcCGxrsxhjIKmMJCsHrHH0dvVGC+W0AMXbxHUVWvcxLLfrJPBz9i8P1HJPIH624xaHmDKkth+IDCCCzF3U2eSIKZt0fGvSnu5CxPdswMi3+QA3Zxctea5IGeV4l/QBSLOAPHHQWe2c060Q5+3hsA0H21KAvYVa9PJs1t22vnOfXajA55XGDjOz2zic6uewRWR4CZkPsXZUsAqrXRlWAXzP4Lp9uKSefxWYT3Hr/4+tUixCwkyL+RSOSHvVzgTaCM7yzJHiaEtu+j9Mk82H8PNCaenb8+RWXftJXw7NB36MdCQVYWcy83nw4mgYqO9+/mHBelNY9lpM9L2DW3tXyy5b01Ht1WQunwwNci0g5OjEevg3+ArQUPhTpZislHeT+1hvSw==
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: crossplane-system
    type: Opaque