---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-secret
  namespace: sealed-secret
spec:
  encryptedData:
    creds: AgB+r5QoFUqcHvZCZidUOdkr3nKByGyedUGv87vmBvNOUSSBOi4vnr8PGYD1oKqzRUO3/9d07kwnDTNuKMjMFHlNWnyZkuEWOz5/+2hAOMjxlCrYMAOI7+CHfKcPX7u1gNm8ro3yDYt1j/YaL4PEbh7ki3bIgvepnFP25dKKR+y+Kz6+mlSrjbP1Hn/otcYbqEG9xceY6yiHnWVdP2rUKO1o2sodIvKIN6j7+62rh8KOmQmzB/7icnaF25Jbrh0l5EMREm10pmwAtb0vXtbAa/fNx52OcyZlVdYSm59euo4rHO4C+zgWzVKw1Lb7TIO20e8yRs/5sDXszOcgiIqoXBg9d0Oz+zh6Ne+d4FpBzmVbuZAPBLuBMj9Y4JmQHWeJXPyLNsLVp0wcU7Vq/cxI7Yg8LHAKhgAhDBRiXSyXDTz5ZWdu3y/7mm5LgzCJMAw+7CLoMbxbXXPboC9wJM9J7Uo5ymM1ihrpvPy2RJ+zYFpdJLLNUHFQMcxxWLikPePFvw7TbHLk9ktcDwEpkJuP1D1mnsXjymAhI79g77ZM/NFpIvl1eNgfMgGfgWmp+eDwzWdFuypczFpraW1zK8bjWTE4A+2TnSUD6kW+BegWlKiWY4wHNxEKLtHJfOPo50Y7klHL46MmqvsgY7MgrVny0MXr1XLhkPqa7/7009NZYgXPCo210xPY0GpS3i5Mb6cIGsImyvoKZKH/vApVAaglv+VJ9i+63F4lfKQsisawmRaY12Zyrk5tFYlN3FZTGdFEhQee7y6i7TPOgqy9xDMyjYBm8UeoL56UHLretRfEkRWSmjaQPImGwZGkoCVEqpKfOwc2YMk3KTSmomjinKkmshZyxWxXS3eCMG10Wm5MjQiC+W4=
  template:
    metadata:
      name: aws-secret
      namespace: sealed-secret
