apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-sa
  namespace: argo-workflows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-role
  namespace: argo-workflows
rules:
  - apiGroups: ["argo.argoproj.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-role-binding
  namespace: argo-workflows
subjects:
  - kind: ServiceAccount
    name: argo-sa
    namespace: argo-workflows
roleRef:
  kind: Role
  name: argo-role
  apiGroup: rbac.authorization.k8s.io