apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: fluentd
  source:
    path: "HelmCharts/fluentd"
    repoURL: "git@ssh.dev.azure.com:v3/Nokia-CNS-SaaS/CNS-SaaS-Dev/sdfc-gitops-poc"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
