apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    env: dev
  namespace: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: valeriivasianovych/flask-app:v6
        ports:
        - name: web
          containerPort: 5000
