  apiVersion: v1
  kind: Service
  metadata:
    name: flask-app-service
    namespace: flask-app
    labels:
      app: flask-app
  spec:
    type: ClusterIP
    ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: web
    selector:
      app: flask-app